### ISSUE TITLE
import  error.

### ISSUE THREAD

**Issue by bkobalava** [kaelzhang/kdj#2]
Hi,
I am hobbyist. I do not know how to import kdj() and how to call it.
① `import kdj from 'kdj'` – gives following error: `(function (exports, require, module, __filename, __dirname) { import kdj from 'kdj'`. 
I replaced with: `const kdj = require('kdj');` It does not give error but Is it correct?

② how to call kdj()? I tryed:
`console.log(kdj(close, low, high, 9, 3, 3, 3, 2).J);`
or
`[K, D, J] = kdj(close, low, high, 9, 3, 3, 3, 2);`
or
```
kdj(close, low, high, 9, 3, 3, 3, 2);
console.log(J);
```

**Comment by kaelzhang** [comment]
1. You cant use `import` in normal `.js` files unless with the help of [babel](https://babeljs.io) or use the [experimental feature `.mjs`](https://nodejs.org/api/esm.html) of nodejs with the extra argument `--experimental-modules` for node. 

2. The return value of `kdj()` is an object, so you should not [destructure](https://babeljs.io/learn-es2015/#destructuring) the value as an array.

```js
// index.js
const kdj = require('kdj')

const {
  K, D, J
} = kdj(
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  [1, 1, 2, 3, 2, 4, 4, 6, 8, 9, 10, 10],
  [2, 2, 3, 4, 6, 8, 7, 9, 11, 11, 12, 14]
)

console.log(K, D, J)
```

**Comment by bkobalava** [comment]
Thank you very much!

**Comment by kaelzhang** [comment]
Close for now~
